"use client";
import { useCallback, useEffect, useState } from "react";
import "./anomaly-history.css";

type StoredAnomaly={objectName:string;objectId?:string;severity:"high"|"medium"|"low";anomaly:string;reason:string;evidence?:string};
type Analysis={reportKind:"campaign"|"keyword"|"searchTerm";startDate:string;endDate:string;modelName:string;status:string;summary?:string;error?:string;anomalies:StoredAnomaly[]};
type History={dates:string[];analysisDate:string|null;analyses:Analysis[];coverage:Array<{reportKind:string;minDate:string|null;maxDate:string|null;rowCount:number;dateCount:number}>;analysisRange?:{minDate:string|null;maxDate:string|null}};
const LABELS={campaign:"广告活动 / 广告组异常",keyword:"投放词异常",searchTerm:"客户搜索词异常"} as const;

export default function AnomalyHistory({accountId,refreshToken=0}:{accountId:string;refreshToken?:number}){
  const [history,setHistory]=useState<History|null>(null),[selectedDate,setSelectedDate]=useState(""),[loading,setLoading]=useState(false),[status,setStatus]=useState("");
  const load=useCallback(async(date?:string)=>{if(!accountId)return;const query=new URLSearchParams({accountId});if(date)query.set("date",date);const response=await fetch(`/api/anomalies?${query}`),data=await response.json();if(!response.ok){setStatus(data.error||"异常历史读取失败");return}setHistory(data);setSelectedDate(data.analysisDate||date||"")},[accountId]);
  useEffect(()=>{void load()},[load,refreshToken]);
  useEffect(()=>{const listener=()=>void analyze();window.addEventListener("amz-analyze-selected",listener);return()=>window.removeEventListener("amz-analyze-selected",listener)},[accountId,selectedDate,loading]);
  async function analyze(){if(!accountId||!selectedDate||loading)return;setLoading(true);setStatus(`正在准备 ${selectedDate} 及此前15天数据`);try{const response=await fetch("/api/anomalies",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accountId,analysisDate:selectedDate})});if(!response.ok){const data=await response.json();throw new Error(data.error||"分析失败")}const reader=response.body!.getReader(),decoder=new TextDecoder();let buffer="",event="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split(/\r?\n/);buffer=lines.pop()??"";for(const line of lines){if(line.startsWith("event:"))event=line.slice(6).trim();else if(line.startsWith("data:")){const data=JSON.parse(line.slice(5));if(event==="status")setStatus(data.text);if(event==="done"){setHistory(data);setSelectedDate(data.analysisDate||selectedDate)}if(event==="error")throw new Error(data.message)}}}}catch(error){setStatus(error instanceof Error?error.message:"分析失败")}finally{setLoading(false);setTimeout(()=>setStatus(""),7000)}}
  const byKind=(kind:keyof typeof LABELS)=>history?.analyses.find(item=>item.reportKind===kind);
  const hasHistory=Boolean(history?.dates.includes(selectedDate));
  return <section className="analysis-history"><div className="analysis-history-head"><div><p className="eyebrow"><span/> AI · DATE-BASED ANOMALY ANALYSIS</p><h3>AI 异常分析历史</h3><small>选择近20天中的任意数据日期；再次分析会覆盖该日期的旧结果。</small></div><label>查看时间<input type="date" value={selectedDate} min={history?.analysisRange?.minDate||undefined} max={history?.analysisRange?.maxDate||undefined} onChange={event=>{setSelectedDate(event.target.value);void load(event.target.value)}}/></label></div>{loading||status?<div className={`dashboard-progress analysis-progress ${!loading?"analysis-error":""}`}><span/>{status||"正在分析…"}</div>:null}<div className="analysis-date-note"><span>{selectedDate||"尚未选择日期"}</span><b>{hasHistory?"已有历史 · 可覆盖重算":"尚未分析"}</b><small>点击页面顶部“数据分析”执行</small></div><div className="coverage-strip">{history?.coverage.map(item=><span key={item.reportKind}><b>{LABELS[item.reportKind as keyof typeof LABELS]}</b>{item.minDate&&item.maxDate?`${item.minDate} 至 ${item.maxDate} · ${item.dateCount}天`:"等待数据"}</span>)}</div><div className="analysis-grid">{(["campaign","keyword","searchTerm"] as const).map(kind=>{const analysis=byKind(kind);return <article className="analysis-panel" key={kind}><div className="analysis-panel-title"><h4>{LABELS[kind]}</h4><span>{analysis?.modelName||"已配置模型"}</span></div>{analysis?.status==="COMPLETED"?<><p className="analysis-summary">{analysis.summary||"分析完成"}</p>{analysis.anomalies.length?<div className="ai-anomaly-list">{analysis.anomalies.map((item,index)=><div className={`ai-anomaly ${item.severity}`} key={`${item.objectId||item.objectName}-${index}`}><header><b>{item.objectName}</b><em>{item.severity==="high"?"高风险":item.severity==="medium"?"中风险":"低风险"}</em></header><strong>{item.anomaly}</strong><p>{item.reason}</p>{item.evidence&&<small>依据：{item.evidence}</small>}</div>)}</div>:<div className="dashboard-empty compact">该类报告未发现明显异常。</div>}</>:<div className="dashboard-empty compact">{analysis?.error||"该日期尚未分析，选择日期后点击顶部“数据分析”。"}</div>}</article>})}</div></section>;
}