"use client";
import { useCallback, useEffect, useState } from "react";
import "./anomaly-history.css";

type StoredAnomaly = { objectName:string;objectId?:string;severity:"high"|"medium"|"low";anomaly:string;reason:string;evidence?:string };
type Analysis = { reportKind:"campaign"|"keyword"|"searchTerm";startDate:string;endDate:string;modelName:string;status:string;summary?:string;error?:string;anomalies:StoredAnomaly[] };
type History = { dates:string[];analysisDate:string|null;analyses:Analysis[];coverage:Array<{reportKind:string;minDate:string|null;maxDate:string|null;rowCount:number;dateCount:number}> };
const LABELS={campaign:"广告活动 / 广告组异常",keyword:"投放词异常",searchTerm:"客户搜索词异常"} as const;

export default function AnomalyHistory({accountId,refreshToken=0}:{accountId:string;refreshToken?:number}){
  const [history,setHistory]=useState<History|null>(null),[loading,setLoading]=useState(false),[status,setStatus]=useState("");
  const load=useCallback(async(date?:string)=>{if(!accountId)return;const query=new URLSearchParams({accountId});if(date)query.set("date",date);const response=await fetch(`/api/anomalies?${query}`),data=await response.json();if(response.ok)setHistory(data)},[accountId]);
  useEffect(()=>{void load()},[load,refreshToken]);
  useEffect(()=>{const listener=()=>void analyze();window.addEventListener("amz-analyze",listener);return()=>window.removeEventListener("amz-analyze",listener)});
  async function analyze(){if(!accountId||loading)return;setLoading(true);setStatus("正在准备近15天数据");try{const response=await fetch("/api/anomalies",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accountId})});if(!response.ok){const data=await response.json();throw new Error(data.error||"分析失败")}const reader=response.body!.getReader(),decoder=new TextDecoder();let buffer="",event="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split(/\r?\n/);buffer=lines.pop()??"";for(const line of lines){if(line.startsWith("event:"))event=line.slice(6).trim();else if(line.startsWith("data:")){const data=JSON.parse(line.slice(5));if(event==="status")setStatus(data.text);if(event==="done")setHistory(data);if(event==="error")throw new Error(data.message)}}}}catch(error){setStatus(error instanceof Error?error.message:"分析失败")}finally{setLoading(false);setTimeout(()=>setStatus(""),5000)}}
  const byKind=(kind:keyof typeof LABELS)=>history?.analyses.find(item=>item.reportKind===kind);
  return <section className="analysis-history"><div className="analysis-history-head"><div><p className="eyebrow"><span/> MIMO · 15 DAY ANOMALY ANALYSIS</p><h3>AI 异常分析历史</h3><small>每天仅分析新拉取的最近15天数据，结果按分析日期永久保留。</small></div><label>查看日期<select value={history?.analysisDate||""} onChange={event=>void load(event.target.value)} disabled={!history?.dates.length}>{history?.dates.length?history.dates.map(date=><option key={date}>{date}</option>):<option value="">暂无记录</option>}</select></label></div>{loading||status?<div className="dashboard-progress analysis-progress"><span/>{status||"正在分析…"}</div>:null}<div className="coverage-strip">{history?.coverage.map(item=><span key={item.reportKind}><b>{LABELS[item.reportKind as keyof typeof LABELS]}</b>{item.minDate&&item.maxDate?`${item.minDate} 至 ${item.maxDate} · ${item.dateCount}天`:"等待初始化"}</span>)}</div><div className="analysis-grid">{(["campaign","keyword","searchTerm"] as const).map(kind=>{const analysis=byKind(kind);return <article className="analysis-panel" key={kind}><div className="analysis-panel-title"><h4>{LABELS[kind]}</h4><span>{analysis?.modelName||"MiMo-v2.5"}</span></div>{analysis?.status==="COMPLETED"?<><p className="analysis-summary">{analysis.summary||"分析完成"}</p>{analysis.anomalies.length?<div className="ai-anomaly-list">{analysis.anomalies.map((item,index)=><div className={`ai-anomaly ${item.severity}`} key={`${item.objectId||item.objectName}-${index}`}><header><b>{item.objectName}</b><em>{item.severity==="high"?"高风险":item.severity==="medium"?"中风险":"低风险"}</em></header><strong>{item.anomaly}</strong><p>{item.reason}</p>{item.evidence&&<small>依据：{item.evidence}</small>}</div>)}</div>:<div className="dashboard-empty compact">该类报告未发现明显异常。</div>}</>:<div className="dashboard-empty compact">{analysis?.error||"完成数据初始化后会自动分析。"}</div>}</article>})}</div></section>
}
