import { appEnv } from "./db";
export type AmazonCredentials={clientId:string;clientSecret:string;refreshToken:string;profileId:string;region:string;advertiserAccountId?:string};
export type McpTool={name:string;description?:string;inputSchema:Record<string,unknown>};
type Rpc={jsonrpc:string;id?:number;result?:any;error?:{code:number;message:string;data?:unknown}};
const MCP_PROTOCOL="2025-06-18";
export class AmazonMcpClient{
  private accessToken:string|null=null;private sessionId:string|null=null;private id=1;
  constructor(private credentials:AmazonCredentials,private mode:"FIXED"|"DYNAMIC"="DYNAMIC"){}
  private async token(){if(this.accessToken)return this.accessToken;const form=new URLSearchParams({grant_type:"refresh_token",refresh_token:this.credentials.refreshToken,client_id:this.credentials.clientId,client_secret:this.credentials.clientSecret});const response=await fetch("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:form});if(!response.ok)throw new Error(`Amazon 授权刷新失败 (${response.status})`);const data=await response.json() as {access_token?:string};if(!data.access_token)throw new Error("Amazon 未返回 access token");this.accessToken=data.access_token;return data.access_token;}
  private async headers(){const h:Record<string,string>={Authorization:`Bearer ${await this.token()}`,"Amazon-Ads-ClientId":this.credentials.clientId,"Amazon-Ads-AI-Account-Selection-Mode":this.mode,Accept:"application/json, text/event-stream","Content-Type":"application/json"};if(this.mode==="FIXED")h["Amazon-Advertising-API-Scope"]=this.credentials.profileId;if(this.sessionId)h["Mcp-Session-Id"]=this.sessionId;return h;}
  private async post(message:unknown):Promise<Rpc[]>{const response=await fetch(appEnv().AMAZON_MCP_URL??"https://advertising-ai.amazon.com/mcp",{method:"POST",headers:await this.headers(),body:JSON.stringify(message)});const sid=response.headers.get("Mcp-Session-Id");if(sid)this.sessionId=sid;const text=await response.text();if(!response.ok)throw new Error(`Amazon MCP 请求失败 (${response.status}): ${text.slice(0,240)}`);if(!text.trim())return[];const contentType=response.headers.get("content-type")??"";if(contentType.includes("text/event-stream")||text.trimStart().startsWith("data:")){return text.split(/\r?\n/).filter(l=>l.startsWith("data:")).map(l=>l.slice(5).trim()).filter(v=>v&&v!=="[DONE]").map(v=>JSON.parse(v) as Rpc);}return[JSON.parse(text) as Rpc];}
  private async initialize(){if(this.sessionId)return;const id=this.id++;const rows=await this.post({jsonrpc:"2.0",id,method:"initialize",params:{protocolVersion:MCP_PROTOCOL,capabilities:{},clientInfo:{name:"amz-pilot",version:"1.0.0"}}});const reply=rows.find(r=>r.id===id);if(reply?.error)throw new Error(reply.error.message);await this.post({jsonrpc:"2.0",method:"notifications/initialized",params:{}});}
  async listTools():Promise<McpTool[]>{await this.initialize();const id=this.id++;const rows=await this.post({jsonrpc:"2.0",id,method:"tools/list",params:{}});const reply=rows.find(r=>r.id===id);if(reply?.error)throw new Error(reply.error.message);return (reply?.result?.tools??[]) as McpTool[];}
  async callTool(name:string,args:Record<string,unknown>):Promise<any>{this.mode=this.modeFor(name);await this.initialize();const id=this.id++;const rows=await this.post({jsonrpc:"2.0",id,method:"tools/call",params:{name,arguments:this.withAccountContext(name,args)}});const reply=rows.find(r=>r.id===id);if(reply?.error)throw new Error(reply.error.message);return reply?.result;}
  private modeFor(name:string):"FIXED"|"DYNAMIC"{return name.includes("query_")||name.includes("delete_target")||name.startsWith("reporting-")?"DYNAMIC":"FIXED";} private withAccountContext(name:string,args:Record<string,unknown>){const dynamic=this.modeFor(name)==="DYNAMIC";const body={...((args.body as Record<string,unknown>)??{})};if(dynamic){if(name.startsWith("reporting-")){if(!body.accessRequestedAccounts&&this.credentials.advertiserAccountId)body.accessRequestedAccounts=[{advertiserAccountId:this.credentials.advertiserAccountId}];}else if(!body.accessRequestedAccount)body.accessRequestedAccount={profileId:this.credentials.profileId};}else{delete body.accessRequestedAccount;delete body.accessRequestedAccounts;}return{...args,body};}
}
export function isWriteTool(name:string){return /(?:^|[-_])(create|update|delete|archive|pause|enable)(?:[-_]|$)/i.test(name)&&!name.startsWith("reporting-");}
export const preferredTools=["ads_accounts-list_ads_accounts","campaign_management-query_campaign","campaign_management-query_ad_group","campaign_management-query_ad","campaign_management-query_target","campaign_management-create_campaign","campaign_management-create_ad_group","campaign_management-create_ad","campaign_management-create_target","campaign_management-update_campaign","campaign_management-update_ad_group","campaign_management-update_ad","campaign_management-update_target","campaign_management-update_target_bid","campaign_management-delete_target","reporting-create_campaign_report","reporting-create_report","reporting-retrieve_report"];