import { d1, ensureSchema } from "./db";
import { randomToken, sha256 } from "./crypto";
export type AppUser={id:string;username:string;role:"admin"|"operator";mustChangePassword:boolean};
export function assertSameOrigin(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Error("请求来源验证失败");}
export async function userFromRequest(request:Request):Promise<AppUser|null>{ await ensureSchema(); const cookie=request.headers.get("cookie")??""; const token=cookie.split(";").map(v=>v.trim()).find(v=>v.startsWith("amz_session="))?.slice(12); if(!token)return null; const hash=await sha256(decodeURIComponent(token)); const row=await d1().prepare(`SELECT u.id,u.username,u.role,u.must_change_password FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).bind(hash,Date.now()).first<{id:string;username:string;role:"admin"|"operator";must_change_password:number}>(); return row?{id:row.id,username:row.username,role:row.role,mustChangePassword:Boolean(row.must_change_password)}:null; }
export async function requireUser(request:Request):Promise<AppUser>{const user=await userFromRequest(request);if(!user)throw new Response(JSON.stringify({error:"请先登录"}),{status:401,headers:{"content-type":"application/json"}});return user;}
export async function createSession(userId:string){const token=randomToken(32);const hash=await sha256(token);const now=Date.now();await d1().prepare(`INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)`).bind(hash,userId,now+7*86400000,now).run();return token;}
export function sessionCookie(token:string){return `amz_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`;}
export function clearSessionCookie(){return `amz_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;}
export async function deleteSession(request:Request){const cookie=request.headers.get("cookie")??"";const token=cookie.split(";").map(v=>v.trim()).find(v=>v.startsWith("amz_session="))?.slice(12);if(token)await d1().prepare(`DELETE FROM sessions WHERE token_hash=?`).bind(await sha256(decodeURIComponent(token))).run();}