import { appEnv } from "./db";
const encoder = new TextEncoder();
function b64(bytes: Uint8Array): string { let s=""; for (const b of bytes) s+=String.fromCharCode(b); return btoa(s); }
function unb64(value: string): Uint8Array { const s=atob(value); return Uint8Array.from(s,c=>c.charCodeAt(0)); }
export function randomToken(bytes=32): string { return b64(crypto.getRandomValues(new Uint8Array(bytes))).replaceAll("+","-").replaceAll("/","_").replaceAll("=",""); }
export async function sha256(value: string): Promise<string> { return b64(new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(value)))); }
export async function hashPassword(password: string, salt?: string): Promise<{hash:string;salt:string}> { const saltBytes=salt?unb64(salt):crypto.getRandomValues(new Uint8Array(16)); const key=await crypto.subtle.importKey("raw",encoder.encode(password+(appEnv().AUTH_PEPPER??"")),"PBKDF2",false,["deriveBits"]); const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:saltBytes as unknown as BufferSource,iterations:100000},key,256); return {hash:b64(new Uint8Array(bits)),salt:b64(saltBytes)}; }
export async function verifyPassword(password:string,salt:string,expected:string):Promise<boolean>{ const {hash}=await hashPassword(password,salt); if(hash.length!==expected.length)return false; let diff=0; for(let i=0;i<hash.length;i++)diff|=hash.charCodeAt(i)^expected.charCodeAt(i); return diff===0; }
async function encryptionKey():Promise<CryptoKey>{ const raw=appEnv().CREDENTIAL_ENCRYPTION_KEY; if(!raw)throw new Error("服务端加密密钥尚未配置"); const bytes=unb64(raw); if(bytes.length!==32)throw new Error("加密密钥格式错误"); return crypto.subtle.importKey("raw",bytes as unknown as BufferSource,{name:"AES-GCM"},false,["encrypt","decrypt"]); }
export async function encryptJson(value:unknown):Promise<string>{ const iv=crypto.getRandomValues(new Uint8Array(12)); const encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv:iv as unknown as BufferSource},await encryptionKey(),encoder.encode(JSON.stringify(value))); return `v1.${b64(iv)}.${b64(new Uint8Array(encrypted))}`; }
export async function decryptJson<T>(value:string):Promise<T>{ const [version,iv,cipher]=value.split("."); if(version!=="v1"||!iv||!cipher)throw new Error("凭证格式错误"); const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(iv) as unknown as BufferSource},await encryptionKey(),unb64(cipher) as unknown as BufferSource); return JSON.parse(new TextDecoder().decode(plain)) as T; }