import { integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(), username: text("username").notNull().unique(),
  passwordHash: text("password_hash").notNull(), passwordSalt: text("password_salt").notNull(),
  role: text("role").notNull().default("operator"), mustChangePassword: integer("must_change_password", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull(),
});
export const sessions = sqliteTable("sessions", { tokenHash: text("token_hash").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), expiresAt: integer("expires_at").notNull(), createdAt: integer("created_at").notNull() });
export const invites = sqliteTable("invites", { codeHash: text("code_hash").primaryKey(), createdBy: text("created_by").notNull().references(() => users.id), maxUses: integer("max_uses").notNull(), useCount: integer("use_count").notNull().default(0), expiresAt: integer("expires_at").notNull(), revokedAt: integer("revoked_at"), createdAt: integer("created_at").notNull() });
export const accounts = sqliteTable("accounts", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), name: text("name").notNull(), region: text("region").notNull(), marketplace: text("marketplace"), timezone: text("timezone"), currency: text("currency"), profileId: text("profile_id").notNull(), advertiserAccountId: text("advertiser_account_id"), encryptedCredentials: text("encrypted_credentials").notNull(), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() }, t => [uniqueIndex("accounts_user_profile_idx").on(t.userId, t.profileId)]);
export const reportJobs = sqliteTable("report_jobs", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: text("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }), reportId: text("report_id"), createTool: text("create_tool").notNull(), requestFingerprint: text("request_fingerprint").notNull(), requestArgs: text("request_args").notNull(), status: text("status").notNull(), error: text("error"), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull(), completedAt: integer("completed_at") }, t => [uniqueIndex("report_jobs_request_idx").on(t.userId, t.accountId, t.requestFingerprint)]);
export const reportFiles = sqliteTable("report_files", { id: text("id").primaryKey(), reportJobId: text("report_job_id").notNull().references(() => reportJobs.id, { onDelete: "cascade" }), partNumber: integer("part_number").notNull(), objectKey: text("object_key").notNull().unique(), filename: text("filename").notNull(), contentType: text("content_type").notNull(), size: integer("size").notNull(), rowCount: integer("row_count").notNull(), summaryJson: text("summary_json").notNull(), createdAt: integer("created_at").notNull() }, t => [uniqueIndex("report_files_job_part_idx").on(t.reportJobId, t.partNumber)]);
export const reportSnapshots = sqliteTable("report_snapshots", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: text("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }), reportType: text("report_type").notNull(), windowKey: text("window_key").notNull(), snapshotDate: text("snapshot_date").notNull(), startDate: text("start_date").notNull(), endDate: text("end_date").notNull(), reportId: text("report_id"), status: text("status").notNull(), attempts: integer("attempts").notNull().default(0), metricsJson: text("metrics_json"), error: text("error"), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull(), completedAt: integer("completed_at") }, t => [uniqueIndex("report_snapshots_window_idx").on(t.accountId, t.reportType, t.windowKey, t.snapshotDate)]);
export const modelSettings = sqliteTable("model_settings", { userId: text("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), baseUrl: text("base_url").notNull(), modelName: text("model_name").notNull(), userAgent: text("user_agent"), encryptedApiKey: text("encrypted_api_key").notNull(), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() });
export const conversations = sqliteTable("conversations", { id: text("id").primaryKey(), userId: text("user_id").notNull(), accountId: text("account_id").notNull(), title: text("title").notNull(), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() });
export const messages = sqliteTable("messages", { id: text("id").primaryKey(), conversationId: text("conversation_id").notNull(), role: text("role").notNull(), content: text("content").notNull(), createdAt: integer("created_at").notNull() });
export const attachments = sqliteTable("attachments", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), conversationId: text("conversation_id"), messageId: text("message_id"), objectKey: text("object_key").notNull().unique(), filename: text("filename").notNull(), contentType: text("content_type").notNull(), size: integer("size").notNull(), createdAt: integer("created_at").notNull() });
export const customSkills = sqliteTable("custom_skills", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), name: text("name").notNull(), description: text("description").notNull(), instructions: text("instructions").notNull(), objectKey: text("object_key").notNull().unique(), filename: text("filename").notNull(), contentType: text("content_type").notNull(), size: integer("size").notNull(), enabled: integer("enabled", { mode: "boolean" }).notNull().default(true), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() }, t => [uniqueIndex("custom_skills_user_name_idx").on(t.userId, t.name)]);
export const approvals = sqliteTable("approvals", { id: text("id").primaryKey(), userId: text("user_id").notNull(), accountId: text("account_id").notNull(), toolName: text("tool_name").notNull(), toolArgs: text("tool_args").notNull(), summary: text("summary").notNull(), status: text("status").notNull(), result: text("result"), createdAt: integer("created_at").notNull(), executedAt: integer("executed_at") });
export const tasks = sqliteTable("tasks", { id: text("id").primaryKey(), userId: text("user_id").notNull(), accountId: text("account_id").notNull(), name: text("name").notNull(), prompt: text("prompt").notNull(), scheduleType: text("schedule_type").notNull(), scheduledTime: text("scheduled_time").notNull(), timezone: text("timezone").notNull(), dayOfWeek: integer("day_of_week"), requireApproval: integer("require_approval", { mode: "boolean" }).notNull().default(true), status: text("status").notNull(), nextRunAt: integer("next_run_at").notNull(), lastRunAt: integer("last_run_at"), createdAt: integer("created_at").notNull() });
export const taskRuns = sqliteTable("task_runs", { id: text("id").primaryKey(), taskId: text("task_id").notNull(), status: text("status").notNull(), detail: text("detail"), startedAt: integer("started_at").notNull(), finishedAt: integer("finished_at") });
export const auditLogs = sqliteTable("audit_logs", { id: text("id").primaryKey(), userId: text("user_id").notNull(), accountId: text("account_id"), action: text("action").notNull(), target: text("target"), detail: text("detail"), outcome: text("outcome").notNull(), createdAt: integer("created_at").notNull() });
export const loginAttempts = sqliteTable("login_attempts", { id: text("id").primaryKey(), username: text("username").notNull(), ipHash: text("ip_hash").notNull(), success: integer("success", { mode: "boolean" }).notNull(), createdAt: integer("created_at").notNull() });